apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  eureka_service_address: http://eureka-0.eureka:6001/eureka

---

apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
    - port: 6001
      name: eureka
  selector:
    app: eureka

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  serviceName: "eureka"
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: ikumaran/service-registry:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 6001
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-password
                  key: PASSWORD
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:7001
            - name: EUREKA_SERVICE_URL_DEFAULT_ZONE
              value: http://service-registry:6001/eureka

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  type: NodePort
  ports:
    - port: 80
      targetPort: 6001
