apiVersion: apps/v1
kind: Deployment
metadata:
  name: synonym-microservice
  labels:
    app: synonym-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synonym-microservice
  template:
    metadata:
      labels:
        app: synonym-microservice
    spec:
      containers:
      - name: synonym-microservice
        image: ikumaran/synonym-microservice:0.0.1-SNAPSHOT
        env:
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-password
                key: PASSWORD
          - name: SPRING_CLOUD_CONFIG_URI
            value: http://config-server:7001
          - name: EUREKA_SERVICE_URL_DEFAULT_ZONE
            value: http://service-registry:6001/eureka
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8002


---

apiVersion: v1
kind: Service
metadata:
  name: synonym-microservice
spec:
  selector:
    app: synonym-microservice
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8002
