version: '3.7'
services:
  config-server:
    image: ${CONFIG_SERVER_IMAGE_REPO_RELEASE}
    hostname: config-server
    ports:
      - "7001:7001"
    volumes:
      - "./docker-logs:/workspace/config-server/logs"
    environment:
      - "SECRET_PASSWORD=${PASSWORD}"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:7001"
    networks:
      - ${GLOBAL_NETWORK:-services}

  service-registry:
    image: ${SERVICE_REGISTRY_IMAGE_REPO_RELEASE}
    hostname: service-registry
    ports:
      - "6001:6001"
    volumes:
      - "./docker-logs:/workspace/service-registry/logs"
    networks:
      - ${GLOBAL_NETWORK:-services}

  synonym-service:
    image: ${SYNONYM_SERVICE_IMAGE_REPO_RELEASE}
    ports:
      - "9001-9002:8002"
    volumes:
      - "./docker-logs:/workspace/synonym-service/logs"
      - "./check-dependent-server-started.sh:/usr/local/bin/check-dependent-server-started.sh"
    entrypoint: [ "check-dependent-server-started.sh" ]
    user: root
    depends_on:
      - config-server
    environment:
      - "SECRET_PASSWORD=${PASSWORD}"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:7001"
      - "EUREKA_SERVICE_URL_DEFAULT_ZONE=http://service-registry:6001/eureka"
    networks:
      - ${GLOBAL_NETWORK:-services}

  antonym-service:
    image: ${ANTONYM_SERVICE_IMAGE_REPO_RELEASE}
    ports:
      - "9003-9004:8001"
    volumes:
      - "./docker-logs:/workspace/synonym-service/logs"
      - "./check-dependent-server-started.sh:/usr/local/bin/check-dependent-server-started.sh"
    entrypoint: [ "check-dependent-server-started.sh" ]
    user: root
    depends_on:
      - config-server
    environment:
      - "SECRET_PASSWORD=${PASSWORD}"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:7001"
      - "EUREKA_SERVICE_URL_DEFAULT_ZONE=http://service-registry:6001/eureka"
    networks:
      - ${GLOBAL_NETWORK:-services}

  words-service:
    image: ${WORDS_SERVICE_IMAGE_REPO_RELEASE}
    ports:
      - "9005-9006:8000"
    volumes:
      - "./docker-logs:/workspace/synonym-service/logs"
      - "./check-dependent-server-started.sh:/usr/local/bin/check-dependent-server-started.sh"
    entrypoint: [ "check-dependent-server-started.sh" ]
    user: root
    depends_on:
      - config-server
    environment:
      - "SECRET_PASSWORD=${PASSWORD}"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:7001"
      - "EUREKA_SERVICE_URL_DEFAULT_ZONE=http://service-registry:6001/eureka"
    networks:
      - ${GLOBAL_NETWORK:-services}

  api-gateway:
    image: ${API_GATEWAY_SERVICE_IMAGE_REPO_RELEASE}
    ports:
      - "8080:5001"
    volumes:
      - "./docker-logs:/workspace/synonym-service/logs"
      - "./check-dependent-server-started.sh:/usr/local/bin/check-dependent-server-started.sh"
    entrypoint: [ "check-dependent-server-started.sh" ]
    user: root
    depends_on:
      - config-server
    environment:
      - "SECRET_PASSWORD=${PASSWORD}"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:7001"
      - "EUREKA_SERVICE_URL_DEFAULT_ZONE=http://service-registry:6001/eureka"
    networks:
      - ${GLOBAL_NETWORK:-services}
